# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dbmanager.ui'
#
# Created: Wed Aug  3 13:59:08 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dbmanagerUI(object):
    def setupUi(self, dbmanagerUI):
        dbmanagerUI.setObjectName(_fromUtf8("dbmanagerUI"))
        dbmanagerUI.resize(1406, 677)
        self.centralwidget = QtGui.QWidget(dbmanagerUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.splitter_2 = QtGui.QSplitter(self.tab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.defaultInfoButton = QtGui.QPushButton(self.layoutWidget)
        self.defaultInfoButton.setObjectName(_fromUtf8("defaultInfoButton"))
        self.horizontalLayout.addWidget(self.defaultInfoButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.databaseDefault = QtGui.QLineEdit(self.layoutWidget)
        self.databaseDefault.setObjectName(_fromUtf8("databaseDefault"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.databaseDefault)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.hostDefault = QtGui.QLineEdit(self.layoutWidget)
        self.hostDefault.setObjectName(_fromUtf8("hostDefault"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.hostDefault)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.portDefault = QtGui.QLineEdit(self.layoutWidget)
        self.portDefault.setObjectName(_fromUtf8("portDefault"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.portDefault)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.userDefault = QtGui.QLineEdit(self.layoutWidget)
        self.userDefault.setObjectName(_fromUtf8("userDefault"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.userDefault)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.newInfoButton = QtGui.QPushButton(self.layoutWidget)
        self.newInfoButton.setObjectName(_fromUtf8("newInfoButton"))
        self.horizontalLayout_2.addWidget(self.newInfoButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self.databaseLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.databaseLineEdit.setObjectName(_fromUtf8("databaseLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.databaseLineEdit)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.databaseHostLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.databaseHostLineEdit.setObjectName(_fromUtf8("databaseHostLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.databaseHostLineEdit)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.databasePortLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.databasePortLineEdit.setObjectName(_fromUtf8("databasePortLineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.databasePortLineEdit)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.databaseUserLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.databaseUserLineEdit.setObjectName(_fromUtf8("databaseUserLineEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.databaseUserLineEdit)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.databasePwLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.databasePwLineEdit.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.databasePwLineEdit.setObjectName(_fromUtf8("databasePwLineEdit"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.databasePwLineEdit)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.textBrowser = QtGui.QTextBrowser(self.layoutWidget)
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout.addWidget(self.textBrowser)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.useDefaultDBRadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.useDefaultDBRadioButton.setChecked(True)
        self.useDefaultDBRadioButton.setObjectName(_fromUtf8("useDefaultDBRadioButton"))
        self.horizontalLayout_3.addWidget(self.useDefaultDBRadioButton)
        self.showMasarConfigButton = QtGui.QPushButton(self.layoutWidget1)
        self.showMasarConfigButton.setObjectName(_fromUtf8("showMasarConfigButton"))
        self.horizontalLayout_3.addWidget(self.showMasarConfigButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.masarConfigTableWidget = QtGui.QTableWidget(self.layoutWidget1)
        self.masarConfigTableWidget.setColumnCount(7)
        self.masarConfigTableWidget.setObjectName(_fromUtf8("masarConfigTableWidget"))
        self.masarConfigTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(6, item)
        self.masarConfigTableWidget.horizontalHeader().setVisible(False)
        self.masarConfigTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.masarConfigTableWidget.verticalHeader().setVisible(False)
        self.masarConfigTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_2.addWidget(self.masarConfigTableWidget)
        self.verticalLayout_8.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.newConfigurationLineEdit = QtGui.QLineEdit(self.tab_2)
        self.newConfigurationLineEdit.setObjectName(_fromUtf8("newConfigurationLineEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.newConfigurationLineEdit)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.newConfigurationDescription = QtGui.QLineEdit(self.tab_2)
        self.newConfigurationDescription.setObjectName(_fromUtf8("newConfigurationDescription"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.newConfigurationDescription)
        self.horizontalLayout_5.addLayout(self.formLayout_3)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.listAvailableSystemPushButton = QtGui.QPushButton(self.tab_2)
        self.listAvailableSystemPushButton.setObjectName(_fromUtf8("listAvailableSystemPushButton"))
        self.horizontalLayout_4.addWidget(self.listAvailableSystemPushButton)
        self.systemComboBox = QtGui.QComboBox(self.tab_2)
        self.systemComboBox.setObjectName(_fromUtf8("systemComboBox"))
        self.systemComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.systemComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.systemLineEdit = QtGui.QLineEdit(self.tab_2)
        self.systemLineEdit.setObjectName(_fromUtf8("systemLineEdit"))
        self.verticalLayout_3.addWidget(self.systemLineEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_5.addWidget(self.line_3)
        self.submiConfigurationPushButton = QtGui.QPushButton(self.tab_2)
        self.submiConfigurationPushButton.setObjectName(_fromUtf8("submiConfigurationPushButton"))
        self.horizontalLayout_5.addWidget(self.submiConfigurationPushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.splitter = QtGui.QSplitter(self.tab_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.listPvGroupPushButton = QtGui.QPushButton(self.layoutWidget2)
        self.listPvGroupPushButton.setObjectName(_fromUtf8("listPvGroupPushButton"))
        self.horizontalLayout_6.addWidget(self.listPvGroupPushButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.pvGroupTreeView = QtGui.QTreeView(self.layoutWidget2)
        self.pvGroupTreeView.setObjectName(_fromUtf8("pvGroupTreeView"))
        self.verticalLayout_4.addWidget(self.pvGroupTreeView)
        self.layoutWidget3 = QtGui.QWidget(self.splitter)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.addPvGroupPushButton = QtGui.QPushButton(self.layoutWidget3)
        self.addPvGroupPushButton.setObjectName(_fromUtf8("addPvGroupPushButton"))
        self.horizontalLayout_7.addWidget(self.addPvGroupPushButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.removePvGroupPushButton = QtGui.QPushButton(self.layoutWidget3)
        self.removePvGroupPushButton.setObjectName(_fromUtf8("removePvGroupPushButton"))
        self.horizontalLayout_7.addWidget(self.removePvGroupPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.newConfigTableWidget = QtGui.QTableWidget(self.layoutWidget3)
        self.newConfigTableWidget.setMouseTracking(True)
        self.newConfigTableWidget.setAcceptDrops(True)
        self.newConfigTableWidget.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.newConfigTableWidget.setRowCount(0)
        self.newConfigTableWidget.setObjectName(_fromUtf8("newConfigTableWidget"))
        self.newConfigTableWidget.setColumnCount(5)
        item = QtGui.QTableWidgetItem()
        self.newConfigTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.newConfigTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.newConfigTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.newConfigTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.newConfigTableWidget.setHorizontalHeaderItem(4, item)
        self.newConfigTableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout_5.addWidget(self.newConfigTableWidget)
        self.verticalLayout_6.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.tabWidget)
        dbmanagerUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(dbmanagerUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1406, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatabases = QtGui.QMenu(self.menubar)
        self.menuDatabases.setObjectName(_fromUtf8("menuDatabases"))
        dbmanagerUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(dbmanagerUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        dbmanagerUI.setStatusBar(self.statusbar)
        self.actionSQLite = QtGui.QAction(dbmanagerUI)
        self.actionSQLite.setCheckable(True)
        self.actionSQLite.setChecked(False)
        self.actionSQLite.setObjectName(_fromUtf8("actionSQLite"))
        self.actionMongoDB = QtGui.QAction(dbmanagerUI)
        self.actionMongoDB.setCheckable(True)
        self.actionMongoDB.setObjectName(_fromUtf8("actionMongoDB"))
        self.actionMySQL = QtGui.QAction(dbmanagerUI)
        self.actionMySQL.setCheckable(True)
        self.actionMySQL.setObjectName(_fromUtf8("actionMySQL"))
        self.menuDatabases.addAction(self.actionSQLite)
        self.menuDatabases.addAction(self.actionMongoDB)
        self.menuDatabases.addAction(self.actionMySQL)
        self.menubar.addAction(self.menuDatabases.menuAction())

        self.retranslateUi(dbmanagerUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionSQLite, QtCore.SIGNAL(_fromUtf8("changed()")), dbmanagerUI.actionsqlitemenu)
        QtCore.QObject.connect(self.actionMongoDB, QtCore.SIGNAL(_fromUtf8("changed()")), dbmanagerUI.actionmongodbmenu)
        QtCore.QObject.connect(self.actionMySQL, QtCore.SIGNAL(_fromUtf8("changed()")), dbmanagerUI.actionmysqlmenu)
        QtCore.QObject.connect(self.defaultInfoButton, QtCore.SIGNAL(_fromUtf8("pressed()")), dbmanagerUI.showdefaultdbinfo)
        QtCore.QObject.connect(self.databaseLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), dbmanagerUI.getdatabasename)
        QtCore.QObject.connect(self.databaseHostLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), dbmanagerUI.getdatabasehost)
        QtCore.QObject.connect(self.databasePortLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), dbmanagerUI.getdatabaseport)
        QtCore.QObject.connect(self.databasePwLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), dbmanagerUI.getdatabasepw)
        QtCore.QObject.connect(self.showMasarConfigButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), dbmanagerUI.showmasarconfigs)
        QtCore.QObject.connect(self.useDefaultDBRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), dbmanagerUI.choosedbsrc)
        QtCore.QObject.connect(self.addPvGroupPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dbmanagerUI.addnewpvgrouprow)
        QtCore.QObject.connect(self.removePvGroupPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dbmanagerUI.removepvgrouprow)
        QtCore.QObject.connect(self.submiConfigurationPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dbmanagerUI.submitmasarconfig)
        QtCore.QObject.connect(self.newConfigTableWidget, QtCore.SIGNAL(_fromUtf8("cellClicked(int,int)")), dbmanagerUI.currentselectedrow)
        QtCore.QObject.connect(self.systemComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), dbmanagerUI.updateselectedsystem)
        QtCore.QObject.connect(self.listAvailableSystemPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dbmanagerUI.updatesystemcombobox)
        QtCore.QObject.connect(self.listPvGroupPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dbmanagerUI.listpvgroups)
        QtCore.QMetaObject.connectSlotsByName(dbmanagerUI)

    def retranslateUi(self, dbmanagerUI):
        dbmanagerUI.setWindowTitle(_translate("dbmanagerUI", "Masar Configuration Manager", None))
        self.defaultInfoButton.setText(_translate("dbmanagerUI", "DB Info (Default)", None))
        self.label.setText(_translate("dbmanagerUI", "Database:", None))
        self.label_2.setText(_translate("dbmanagerUI", "Host:", None))
        self.label_3.setText(_translate("dbmanagerUI", "Port:", None))
        self.label_7.setText(_translate("dbmanagerUI", "User:", None))
        self.newInfoButton.setText(_translate("dbmanagerUI", "DB Info (by user)", None))
        self.label_13.setText(_translate("dbmanagerUI", "Database:", None))
        self.label_11.setText(_translate("dbmanagerUI", "Host:", None))
        self.label_12.setText(_translate("dbmanagerUI", "Port:", None))
        self.label_10.setText(_translate("dbmanagerUI", "User:", None))
        self.label_14.setText(_translate("dbmanagerUI", "Password:", None))
        self.textBrowser.setHtml(_translate("dbmanagerUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt;\">View all existing MASAR configurations. There are 2 choices available:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt;\">1. Defcault configuration, which would be loaded from masarservice.conf;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt;\">2. Specify DB information.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Lucida Grande UI\'; font-size:13pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt;\">If &quot;Use Default DB&quot; is selected, this will read information from default one, </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt;\">otherwise, read information from user specified database.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.Lucida Grande UI\'; font-size:13pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt;\">From this UI tool, MASAR admin could be able update status of existing configuration</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt;\">to either &quot;active&quot;, or &quot;inactive&quot;.</span></p></body></html>", None))
        self.useDefaultDBRadioButton.setText(_translate("dbmanagerUI", "Use Default DB", None))
        self.showMasarConfigButton.setText(_translate("dbmanagerUI", "Show Configs", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dbmanagerUI", "id", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dbmanagerUI", "name", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dbmanagerUI", "description", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("dbmanagerUI", "date", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("dbmanagerUI", "version", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("dbmanagerUI", "status", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("dbmanagerUI", "update", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("dbmanagerUI", "View/Update Configurations", None))
        self.label_4.setText(_translate("dbmanagerUI", "Name:", None))
        self.label_5.setText(_translate("dbmanagerUI", "Description:", None))
        self.label_6.setText(_translate("dbmanagerUI", "System:", None))
        self.listAvailableSystemPushButton.setText(_translate("dbmanagerUI", "List System", None))
        self.systemComboBox.setItemText(0, _translate("dbmanagerUI", "Others", None))
        self.submiConfigurationPushButton.setText(_translate("dbmanagerUI", "Create New Configuration", None))
        self.listPvGroupPushButton.setText(_translate("dbmanagerUI", "Browse PV Group", None))
        self.addPvGroupPushButton.setText(_translate("dbmanagerUI", "Add PV Group", None))
        self.removePvGroupPushButton.setText(_translate("dbmanagerUI", "Remove PV Group", None))
        item = self.newConfigTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dbmanagerUI", "pv group name", None))
        item = self.newConfigTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dbmanagerUI", "pv group description", None))
        item = self.newConfigTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dbmanagerUI", "show pvs", None))
        item = self.newConfigTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("dbmanagerUI", "choose pv file", None))
        item = self.newConfigTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("dbmanagerUI", "pv file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("dbmanagerUI", "New Configuration", None))
        self.menuDatabases.setTitle(_translate("dbmanagerUI", "Databases", None))
        self.actionSQLite.setText(_translate("dbmanagerUI", "SQLite", None))
        self.actionMongoDB.setText(_translate("dbmanagerUI", "MongoDB", None))
        self.actionMySQL.setText(_translate("dbmanagerUI", "MySQL", None))

