#Makefile at top of application tree
TOP = ..
include $(TOP)/configure/CONFIG

DIRS += util

DIRS += client

DIRS += server
server_DEPEND_DIRS = util

DIRS += python

DIRS += masarServiceRun

include $(TOP)/configure/RULES_DIRS


