#Makefile at top of application tree
TOP = ..
include $(TOP)/configure/CONFIG

DIRS += clientCPP
clientApp_DEPEND_DIRS = configure

DIRS += serverCPP
serverApp_DEPEND_DIRS = configure

DIRS += dslPYIRMIS
dslPYIRMISApp_DEPEND_DIRS = configure

include $(TOP)/configure/RULES_DIRS


