TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testCallPYIRMIS
testCallPYIRMIS_SRCS += testCallPYIRMIS.cpp
testCallPYIRMIS_LIBS += dslPYIRMIS pvData Com


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

