TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testezchannelRPC
testezchannelRPC_SRCS += testezchannelRPC.cpp
testezchannelRPC_LIBS += gather nt pvIOC pvAccess pvData Com
testezchannelRPC_LIBS += $(PYTHON)

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

