TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testezchannelRPC
testezchannelRPC_SRCS += testezchannelRPC.cpp
testezchannelRPC_LIBS += nt pvIOC pvAccess pvData Com masarClient
testezchannelRPC_LIBS += $(PYTHON)

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

