#!/usr/bin/python

import sys
import os

try:
    import ui.masar as masar
except:
    import sys
    root = os.path.abspath(os.path.dirname(__file__))
    sys.path.append("/".join([root, "../python"]))
    sys.path.append("/".join([root, "src/python"]))
    sys.path.append("/".join([root, "../python/src/client"]))
#    sys.path.append("/".join([root, "python/src/server"]))
    import ui.masar as masar
    
masar.main()
