#!/usr/bin/python

import sys


try:
    import ui.masar as masar
except:
    import sys
    root = "/Users/shengb/V4/std.tr1/masarService"
    sys.path.append("/".join([root, "python"]))
    sys.path.append("/".join([root, "cpp/src/python"]))
    sys.path.append("/".join([root, "python/src/client"]))
#    sys.path.append("/".join([root, "python/src/server"]))
    import ui.masar as masar
    
masar.main()
