#!/usr/bin/python

import sys
import os

channel = "masarService"
args = sys.argv[1:]
if len(args) > 0:
    channel = args[0]

#try:
#    import ui.masar as masar
#except:
#    import sys
#    root = os.path.abspath(os.path.dirname(__file__))
#    sys.path.append("/".join([root, "../python"]))
#    sys.path.append("/".join([root, "src/python"]))
#    sys.path.append("/".join([root, "../python/client"]))
#    import ui.masar as masar
import masarclient.ui.masar as masar   
masar.main(channelname=channel)
