TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testCallPY
testCallPY_SRCS += testCallPY.cpp
testCallPY_LIBS += nt pvIOC pvAccess pvData Com masarServer masarClient
testCallPY_LIBS += $(PYTHON)

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

