TOP = ..
include $(TOP)/configure/CONFIG
include $(TOP)/configure/CONFIG_PY

PY += masarclient/__init__.py
PY += masarclient/alarm.py
PY += masarclient/channelRPC.py
PY += masarclient/control.py
PY += masarclient/display.py
PY += masarclient/gatherV3Data.py
PY += masarclient/masarClient.py
PY += masarclient/masarClient2.py
PY += masarclient/ntmultiChannel.py
PY += masarclient/ntnameValue.py
PY += masarclient/ntscalar.py
PY += masarclient/nttable.py
PY += masarclient/timeStamp.py
PY += masarclient/ui/__init__.py
PY += masarclient/ui/authendlg.py
PY += masarclient/ui/commentdetail.py
PY += masarclient/ui/commentdlg.py
PY += masarclient/ui/finddlg.py
PY += masarclient/ui/getmasarconfig.py
PY += masarclient/ui/gradualput.py
PY += masarclient/ui/masar.py
PY += masarclient/ui/masarRC_rc.py
PY += masarclient/ui/selectrefsnapshotdlg.py
PY += masarclient/ui/showarrayvaluedlg.py
PY += masarclient/ui/ui_commentdetail.py
PY += masarclient/ui/ui_commentdiag.py
PY += masarclient/ui/ui_masar.py
PY += masarclient/ui/verifysetpoint.py

PY += masarserver/__init__.py
PY += masarserver/dslPY.py
PY += masarserver/dslPYMongo.py
PY += masarserver/dslPYSQLite.py

PY += masarutils/__init__.py
PY += masarutils/addmasarconfigs.py
PY += masarutils/masarconfigmanager.py
PY += masarutils/migratesqlite2mongo.py
PY += masarutils/ui_dbmanager.py

PY += pymasarmongo/__init__.py
PY += pymasarmongo/config/__init__.py
PY += pymasarmongo/config/_config.py
PY += pymasarmongo/db/__init__.py
PY += pymasarmongo/db/utils.py
PY += pymasarmongo/pymasarmongo/__init__.py
PY += pymasarmongo/pymasarmongo/_logger.py
PY += pymasarmongo/pymasarmongo/pymasar.py
PY += pymasarmongo/utils/__init__.py

PY += pymasarsqlite/__init__.py
PY += pymasarsqlite/db/__init__.py
PY += pymasarsqlite/db/configmasardb.py
PY += pymasarsqlite/db/createmasardb.py
PY += pymasarsqlite/db/masarsqlite.py
PY += pymasarsqlite/db/settings.py
PY += pymasarsqlite/masardata/__init__.py
PY += pymasarsqlite/masardata/masardata.py
PY += pymasarsqlite/pvgroup/__init__.py
PY += pymasarsqlite/pvgroup/pv.py
PY += pymasarsqlite/pvgroup/pvgroup.py
PY += pymasarsqlite/service/__init__.py
PY += pymasarsqlite/service/service.py
PY += pymasarsqlite/service/serviceconfig.py
PY += pymasarsqlite/service/serviceconfigprop.py
PY += pymasarsqlite/service/serviceevent.py
PY += pymasarsqlite/utils.py

PY += pymasarsqlite/db/masar-sqlite.sql

PY += minimasar/__init__.py
PY += minimasar/db.py
PY += minimasar/ops.py
PY += minimasar/test/__init__.py
PY += minimasar/test/test_db.py
PY += minimasar/test/test_ops.py

include $(TOP)/configure/RULES
include $(TOP)/configure/RULES_PY

