TOP = ..
include $(TOP)/configure/CONFIG
DIRS += testCallPY
DIRS += testClientLocal
DIRS += testGatherV3ScalarData
DIRS += testezchannelRPC
DIRS += masarServiceRun
include $(TOP)/configure/RULES_DIRS

