# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dbmanager.ui'
#
# Created: Tue Aug 26 08:46:25 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dbmanagerUI(object):
    def setupUi(self, dbmanagerUI):
        dbmanagerUI.setObjectName(_fromUtf8("dbmanagerUI"))
        dbmanagerUI.resize(1685, 981)
        self.centralwidget = QtGui.QWidget(dbmanagerUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1661, 911))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.masarConfigTableWidget = QtGui.QTableWidget(self.tab)
        self.masarConfigTableWidget.setGeometry(QtCore.QRect(290, 30, 1361, 851))
        self.masarConfigTableWidget.setColumnCount(7)
        self.masarConfigTableWidget.setObjectName(_fromUtf8("masarConfigTableWidget"))
        self.masarConfigTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.masarConfigTableWidget.setHorizontalHeaderItem(6, item)
        self.masarConfigTableWidget.horizontalHeader().setVisible(False)
        self.masarConfigTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.masarConfigTableWidget.verticalHeader().setVisible(False)
        self.masarConfigTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.showMasarConfigButton = QtGui.QPushButton(self.tab)
        self.showMasarConfigButton.setGeometry(QtCore.QRect(410, 0, 114, 32))
        self.showMasarConfigButton.setObjectName(_fromUtf8("showMasarConfigButton"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(1180, 0, 114, 32))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.defaultInfoButton = QtGui.QPushButton(self.tab)
        self.defaultInfoButton.setGeometry(QtCore.QRect(10, 0, 171, 32))
        self.defaultInfoButton.setObjectName(_fromUtf8("defaultInfoButton"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 62, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 40, 62, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 62, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.newInfoButton = QtGui.QPushButton(self.tab)
        self.newInfoButton.setGeometry(QtCore.QRect(10, 180, 171, 32))
        self.newInfoButton.setObjectName(_fromUtf8("newInfoButton"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 62, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.databaseDefault = QtGui.QTextBrowser(self.tab)
        self.databaseDefault.setGeometry(QtCore.QRect(80, 30, 191, 31))
        self.databaseDefault.setObjectName(_fromUtf8("databaseDefault"))
        self.hostDefault = QtGui.QTextBrowser(self.tab)
        self.hostDefault.setGeometry(QtCore.QRect(80, 60, 191, 31))
        self.hostDefault.setObjectName(_fromUtf8("hostDefault"))
        self.portDefault = QtGui.QTextBrowser(self.tab)
        self.portDefault.setGeometry(QtCore.QRect(80, 90, 191, 31))
        self.portDefault.setObjectName(_fromUtf8("portDefault"))
        self.userDefault = QtGui.QTextBrowser(self.tab)
        self.userDefault.setGeometry(QtCore.QRect(80, 120, 191, 31))
        self.userDefault.setObjectName(_fromUtf8("userDefault"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 300, 62, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 240, 62, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(10, 270, 62, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(10, 210, 62, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.databaseLineEdit = QtGui.QLineEdit(self.tab)
        self.databaseLineEdit.setGeometry(QtCore.QRect(80, 210, 191, 31))
        self.databaseLineEdit.setObjectName(_fromUtf8("databaseLineEdit"))
        self.databaseHostLineEdit = QtGui.QLineEdit(self.tab)
        self.databaseHostLineEdit.setGeometry(QtCore.QRect(80, 240, 191, 31))
        self.databaseHostLineEdit.setObjectName(_fromUtf8("databaseHostLineEdit"))
        self.databasePortLineEdit = QtGui.QLineEdit(self.tab)
        self.databasePortLineEdit.setGeometry(QtCore.QRect(80, 270, 191, 31))
        self.databasePortLineEdit.setObjectName(_fromUtf8("databasePortLineEdit"))
        self.databaseUserLineEdit = QtGui.QLineEdit(self.tab)
        self.databaseUserLineEdit.setGeometry(QtCore.QRect(80, 300, 191, 31))
        self.databaseUserLineEdit.setObjectName(_fromUtf8("databaseUserLineEdit"))
        self.databasePwLineEdit = QtGui.QLineEdit(self.tab)
        self.databasePwLineEdit.setGeometry(QtCore.QRect(80, 330, 191, 31))
        self.databasePwLineEdit.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.databasePwLineEdit.setObjectName(_fromUtf8("databasePwLineEdit"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(10, 330, 62, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.useDefaultDBRadioButton = QtGui.QRadioButton(self.tab)
        self.useDefaultDBRadioButton.setGeometry(QtCore.QRect(290, 5, 121, 20))
        self.useDefaultDBRadioButton.setChecked(True)
        self.useDefaultDBRadioButton.setObjectName(_fromUtf8("useDefaultDBRadioButton"))
        self.textBrowser = QtGui.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(0, 390, 281, 491))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(40, 30, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.newConfigurationLineEdit = QtGui.QLineEdit(self.tab_2)
        self.newConfigurationLineEdit.setGeometry(QtCore.QRect(90, 20, 381, 31))
        self.newConfigurationLineEdit.setObjectName(_fromUtf8("newConfigurationLineEdit"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.newConfigurationDescription = QtGui.QLineEdit(self.tab_2)
        self.newConfigurationDescription.setGeometry(QtCore.QRect(90, 50, 701, 31))
        self.newConfigurationDescription.setObjectName(_fromUtf8("newConfigurationDescription"))
        self.newConfigTableWidget = QtGui.QTableWidget(self.tab_2)
        self.newConfigTableWidget.setGeometry(QtCore.QRect(450, 130, 1201, 741))
        self.newConfigTableWidget.setMouseTracking(True)
        self.newConfigTableWidget.setAcceptDrops(True)
        self.newConfigTableWidget.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.newConfigTableWidget.setRowCount(0)
        self.newConfigTableWidget.setObjectName(_fromUtf8("newConfigTableWidget"))
        self.newConfigTableWidget.setColumnCount(5)
        item = QtGui.QTableWidgetItem()
        self.newConfigTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.newConfigTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.newConfigTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.newConfigTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.newConfigTableWidget.setHorizontalHeaderItem(4, item)
        self.newConfigTableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.addPvGroupPushButton = QtGui.QPushButton(self.tab_2)
        self.addPvGroupPushButton.setGeometry(QtCore.QRect(570, 100, 114, 32))
        self.addPvGroupPushButton.setObjectName(_fromUtf8("addPvGroupPushButton"))
        self.removePvGroupPushButton = QtGui.QPushButton(self.tab_2)
        self.removePvGroupPushButton.setGeometry(QtCore.QRect(1460, 100, 141, 32))
        self.removePvGroupPushButton.setObjectName(_fromUtf8("removePvGroupPushButton"))
        self.submiConfigurationPushButton = QtGui.QPushButton(self.tab_2)
        self.submiConfigurationPushButton.setGeometry(QtCore.QRect(1400, 40, 201, 32))
        self.submiConfigurationPushButton.setObjectName(_fromUtf8("submiConfigurationPushButton"))
        self.line = QtGui.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(0, 90, 1651, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(810, 30, 61, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.systemComboBox = QtGui.QComboBox(self.tab_2)
        self.systemComboBox.setGeometry(QtCore.QRect(1010, 20, 121, 31))
        self.systemComboBox.setObjectName(_fromUtf8("systemComboBox"))
        self.systemComboBox.addItem(_fromUtf8(""))
        self.listAvailableSystemPushButton = QtGui.QPushButton(self.tab_2)
        self.listAvailableSystemPushButton.setGeometry(QtCore.QRect(870, 20, 131, 32))
        self.listAvailableSystemPushButton.setObjectName(_fromUtf8("listAvailableSystemPushButton"))
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(795, 15, 16, 81))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(1330, 15, 16, 81))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.systemLineEdit = QtGui.QLineEdit(self.tab_2)
        self.systemLineEdit.setGeometry(QtCore.QRect(1010, 50, 311, 41))
        self.systemLineEdit.setObjectName(_fromUtf8("systemLineEdit"))
        self.listPvGroupPushButton = QtGui.QPushButton(self.tab_2)
        self.listPvGroupPushButton.setGeometry(QtCore.QRect(0, 100, 141, 32))
        self.listPvGroupPushButton.setObjectName(_fromUtf8("listPvGroupPushButton"))
        self.pvGroupTreeView = QtGui.QTreeView(self.tab_2)
        self.pvGroupTreeView.setGeometry(QtCore.QRect(10, 130, 401, 741))
        self.pvGroupTreeView.setObjectName(_fromUtf8("pvGroupTreeView"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        dbmanagerUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(dbmanagerUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1685, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatabases = QtGui.QMenu(self.menubar)
        self.menuDatabases.setObjectName(_fromUtf8("menuDatabases"))
        dbmanagerUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(dbmanagerUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        dbmanagerUI.setStatusBar(self.statusbar)
        self.actionSQLite = QtGui.QAction(dbmanagerUI)
        self.actionSQLite.setCheckable(True)
        self.actionSQLite.setChecked(False)
        self.actionSQLite.setObjectName(_fromUtf8("actionSQLite"))
        self.actionMongoDB = QtGui.QAction(dbmanagerUI)
        self.actionMongoDB.setCheckable(True)
        self.actionMongoDB.setObjectName(_fromUtf8("actionMongoDB"))
        self.actionMySQL = QtGui.QAction(dbmanagerUI)
        self.actionMySQL.setCheckable(True)
        self.actionMySQL.setObjectName(_fromUtf8("actionMySQL"))
        self.menuDatabases.addAction(self.actionSQLite)
        self.menuDatabases.addAction(self.actionMongoDB)
        self.menuDatabases.addAction(self.actionMySQL)
        self.menubar.addAction(self.menuDatabases.menuAction())

        self.retranslateUi(dbmanagerUI)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionSQLite, QtCore.SIGNAL(_fromUtf8("changed()")), dbmanagerUI.actionsqlitemenu)
        QtCore.QObject.connect(self.actionMongoDB, QtCore.SIGNAL(_fromUtf8("changed()")), dbmanagerUI.actionmongodbmenu)
        QtCore.QObject.connect(self.actionMySQL, QtCore.SIGNAL(_fromUtf8("changed()")), dbmanagerUI.actionmysqlmenu)
        QtCore.QObject.connect(self.defaultInfoButton, QtCore.SIGNAL(_fromUtf8("pressed()")), dbmanagerUI.showdefaultdbinfo)
        QtCore.QObject.connect(self.databaseLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), dbmanagerUI.getdatabasename)
        QtCore.QObject.connect(self.databaseHostLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), dbmanagerUI.getdatabasehost)
        QtCore.QObject.connect(self.databasePortLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), dbmanagerUI.getdatabaseport)
        QtCore.QObject.connect(self.databasePwLineEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), dbmanagerUI.getdatabasepw)
        QtCore.QObject.connect(self.showMasarConfigButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), dbmanagerUI.showmasarconfigs)
        QtCore.QObject.connect(self.useDefaultDBRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), dbmanagerUI.choosedbsrc)
        QtCore.QObject.connect(self.addPvGroupPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dbmanagerUI.addnewpvgrouprow)
        QtCore.QObject.connect(self.removePvGroupPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dbmanagerUI.removepvgrouprow)
        QtCore.QObject.connect(self.submiConfigurationPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dbmanagerUI.submitmasarconfig)
        QtCore.QObject.connect(self.newConfigTableWidget, QtCore.SIGNAL(_fromUtf8("cellClicked(int,int)")), dbmanagerUI.currentselectedrow)
        QtCore.QObject.connect(self.systemComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), dbmanagerUI.updateselectedsystem)
        QtCore.QObject.connect(self.listAvailableSystemPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dbmanagerUI.updatesystemcombobox)
        QtCore.QObject.connect(self.listPvGroupPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), dbmanagerUI.listpvgroups)
        QtCore.QMetaObject.connectSlotsByName(dbmanagerUI)

    def retranslateUi(self, dbmanagerUI):
        dbmanagerUI.setWindowTitle(_translate("dbmanagerUI", "Masar Configuration Manager", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dbmanagerUI", "id", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dbmanagerUI", "name", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dbmanagerUI", "description", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("dbmanagerUI", "date", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("dbmanagerUI", "version", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("dbmanagerUI", "status", None))
        item = self.masarConfigTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("dbmanagerUI", "update", None))
        self.showMasarConfigButton.setText(_translate("dbmanagerUI", "Show Configs", None))
        self.pushButton.setText(_translate("dbmanagerUI", "Update Status", None))
        self.defaultInfoButton.setText(_translate("dbmanagerUI", "DB Info (Default)", None))
        self.label_3.setText(_translate("dbmanagerUI", "Port:", None))
        self.label.setText(_translate("dbmanagerUI", "Database:", None))
        self.label_2.setText(_translate("dbmanagerUI", "Host:", None))
        self.newInfoButton.setText(_translate("dbmanagerUI", "DB Info (by user)", None))
        self.label_7.setText(_translate("dbmanagerUI", "User:", None))
        self.label_10.setText(_translate("dbmanagerUI", "User:", None))
        self.label_11.setText(_translate("dbmanagerUI", "Host:", None))
        self.label_12.setText(_translate("dbmanagerUI", "Port:", None))
        self.label_13.setText(_translate("dbmanagerUI", "Database:", None))
        self.label_14.setText(_translate("dbmanagerUI", "Password:", None))
        self.useDefaultDBRadioButton.setText(_translate("dbmanagerUI", "Use Default DB", None))
        self.textBrowser.setHtml(_translate("dbmanagerUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">View all existing MASAR configurations. There are 2 choices available:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. Defcault configuration, which would be loaded from masarservice.conf;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Specify DB information.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If &quot;Use Default DB&quot; is selected, this will read information from default one, </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">otherwise, read information from user specified database.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">From this UI tool, MASAR admin could be able update status of existing configuration</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">to either &quot;active&quot;, or &quot;inactive&quot;.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("dbmanagerUI", "View/Update Configurations", None))
        self.label_4.setText(_translate("dbmanagerUI", "Name:", None))
        self.label_5.setText(_translate("dbmanagerUI", "Description:", None))
        item = self.newConfigTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dbmanagerUI", "pv group name", None))
        item = self.newConfigTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dbmanagerUI", "pv group description", None))
        item = self.newConfigTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dbmanagerUI", "show pvs", None))
        item = self.newConfigTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("dbmanagerUI", "choose pv file", None))
        item = self.newConfigTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("dbmanagerUI", "pv file", None))
        self.addPvGroupPushButton.setText(_translate("dbmanagerUI", "Add PV Group", None))
        self.removePvGroupPushButton.setText(_translate("dbmanagerUI", "Remove PV Group", None))
        self.submiConfigurationPushButton.setText(_translate("dbmanagerUI", "Create New Configuration", None))
        self.label_6.setText(_translate("dbmanagerUI", "System:", None))
        self.systemComboBox.setItemText(0, _translate("dbmanagerUI", "Others", None))
        self.listAvailableSystemPushButton.setText(_translate("dbmanagerUI", "List System", None))
        self.listPvGroupPushButton.setText(_translate("dbmanagerUI", "Browse PV Group", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("dbmanagerUI", "New Configuration", None))
        self.menuDatabases.setTitle(_translate("dbmanagerUI", "Databases", None))
        self.actionSQLite.setText(_translate("dbmanagerUI", "SQLite", None))
        self.actionMongoDB.setText(_translate("dbmanagerUI", "MongoDB", None))
        self.actionMySQL.setText(_translate("dbmanagerUI", "MySQL", None))

