name: MASAR

on: [push, pull_request]

jobs:
  pytest:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "2.7"
            profile: deb9
          - python: "3.7"
            profile: deb10
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        if: matrix.python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install --only-binary numpy -r requirements-${{ matrix.profile }}.txt
          python -m pip install p4p nose
      - name: Test
        run: |
          cd python
          python -m nose -v minimasar
